In [9]:
#exercice1
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b=a.tolist()
print(b)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [11]:
#exercice2
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
r=np.trace(a)
print(a)
print(r)
            


[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [17]:
#exercice3
import numpy as np
a = np.array([[3,8,5],[0,7,2],[6,1,8]])
y=int(input("choisisez un nombre"))
r=a[a>y]
print(r)


choisisez un nombre3
[8 5 7 6 8]


In [20]:
#exercice4
import numpy as np
a = np.array([[3,8,5],[0,7,2],[6,1,8]])
b= np.array([[0,1,2],[3,4,5],[6,7,8]])
c=a+b
print(c)



[[ 3  9  7]
 [ 3 11  7]
 [12  8 16]]


In [29]:
import numpy as np
a = np.array([[1, 4, 5, 12], 
    [5, 8, 9, 0],
    [6, 7, 11, 19]])
for i in a:
    y=i.mean()
    print (y)
    for j in i:
        Y=j-y
        print("Y=",Y)



5.5
Y= -4.5
Y= -1.5
Y= -0.5
Y= 6.5
5.5
Y= -0.5
Y= 2.5
Y= 3.5
Y= -5.5
10.75
Y= -4.75
Y= -3.75
Y= 0.25
Y= 8.25
